language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# commands to check code quality and run tests
script:
  - pylint ds_utils --ignore-patterns="test_.*?py" --max-line-length=120
  - pytest